apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ingress.secretName }}
  namespace: {{ .Values.ingress.namespace }}
  labels:
    {{- include "eso.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.ingress.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.ingress.secretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.ingress.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ $.Values.ingress.vaultSecretPath | quote }}
        property: {{ .vaultKey | quote }}
    {{- end }}
