apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: {{ .Values.grafana.namespace }}
  labels:
    {{- include "eso.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.grafana.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.grafana.secretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.grafana.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ $.Values.grafana.vaultSecretPath | quote }}
        property: {{ .vaultKey | quote }}
    {{- end }}
