apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-approle-credentials
  namespace: {{ .Values.secretStore.namespace }}
  labels:
    {{- include "eso.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.aws.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.vault.approleSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: "role-id"
      remoteRef:
        key: {{ .Values.aws.ssm.roleIdPath | quote }}
    - secretKey: "secret-id"
      remoteRef:
        key: {{ .Values.aws.ssm.secretIdPath | quote }}
