apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.aws.secretStoreName }}
  namespace: {{ .Values.secretStore.namespace }}
  labels:
    {{- include "eso.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws.region | quote }}
